### ISSUE TITLE
Cannot open files

### ISSUE THREAD

**Issue by jhg39** [isaacphysics/isaac-editor#187]
Issue found in 73cd0144fb10f413c07ac989e67170926b1abc38

<Describe issue here>
When I try to open a file, nothing appears on the page, yet I am still able to use the 'preview on staging'.

![image](https://user-images.githubusercontent.com/60006629/130631243-6fbc95a0-79ee-402c-9d5f-c48c8e1cb237.png)

**Comment by jsharkey13** [comment]
Weird! If you can see the file list on the left hand side, there's no reason you shouldn't see the page itself. Have you tried reloading with Ctrl-F5, or opening Developer Tools in the browser (often F12 or Ctrl-Shift-i ), going to the Network tab of the box that pops up and clicking "Disable Cache" and then reloading the page with that box open?
If that fails, does the Console tab have any obvious errors in it?

**Comment by jhg39** [comment]
Hi James,

For some reason it’s back up and running again on Microsoft Edge, it was just yesterday. I switched to Chrome temporarily, and Chrome was perfectly fine.

Many thanks,
Jia
